"use client";
import { useEffect,useState } from "react";
import { Page,Notice,History,PrivateFile,buttonClass,fieldClass } from "./Phase4UI";
import { requestJson,errorMessage,statusLabel,type OfficialRecord } from "@/lib/phase4-client";
import { officialLabels,documentLabels,positionLabels } from "@/lib/official-labels";
export default function OfficialReview({scope}:{scope:"club"|"staff"}) {
  const [rows,setRows]=useState<OfficialRecord[]>([]);const [busy,setBusy]=useState(true);const [message,setMessage]=useState("");const [reasons,setReasons]=useState<Record<string,string>>({});
  const endpoint="/api/"+scope+"/officials";
  useEffect(()=>{let active=true;requestJson<{applications:OfficialRecord[]}>(endpoint).then(d=>{if(active)setRows(d.applications);}).catch(e=>{if(active)setMessage(errorMessage(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[endpoint]);
  async function load(){setBusy(true);try{setRows((await requestJson<{applications:OfficialRecord[]}>(endpoint)).applications);}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}}
  async function review(a:OfficialRecord,action:string){setBusy(true);setMessage("");try{await requestJson(endpoint,{id:a.id,version:a.version,action,reason:reasons[a.id]});await load();setMessage("บันทึกผลพิจารณาแล้ว");}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}}
  return <Page title={"พิจารณาเจ้าหน้าที่ทีม — "+(scope==="club"?"ชมรม":"กองกิจฯ")}><Notice text={message}/><button className={buttonClass} disabled={busy} onClick={()=>void load()}>โหลดข้อมูลล่าสุด</button>{busy&&<p>กำลังโหลด…</p>}{!busy&&!rows.length&&<p>ยังไม่มีใบสมัครในคิว</p>}{rows.map(a=><section className="space-y-3 rounded-xl border bg-white p-5" key={a.id}><h2 className="text-lg font-bold">{a.profile.firstName} {a.profile.lastName} · {a.competition.name}</h2><p>{a.club?.name} · {statusLabel[a.status]||a.status}</p><details><summary>ข้อมูลและเอกสารผู้สมัคร</summary><dl className="grid gap-2 py-3 md:grid-cols-2">{Object.entries(a.profile).map(([key,value])=><div key={key}><dt className="text-sm text-slate-500">{officialLabels[key]||key}</dt><dd>{key==="appliedPosition"?positionLabels[value]||value:value||"—"}</dd></div>)}</dl><ul className="space-y-2">{Object.entries(a.documents).map(([key,id])=><li key={key}>{documentLabels[key]}: <PrivateFile id={id}/></li>)}</ul></details>{a.status===(scope==="club"?"SUBMITTED":"CLUB_APPROVED")&&<div className="flex flex-wrap gap-3"><input aria-label={"เหตุผลปฏิเสธ "+a.profile.firstName} placeholder="เหตุผลเมื่อปฏิเสธ" className={fieldClass} value={reasons[a.id]??""} onChange={e=>setReasons({...reasons,[a.id]:e.target.value})}/><button className={buttonClass} disabled={busy} onClick={()=>void review(a,"approve")}>อนุมัติ{scope==="club"?"และส่งต่อกองกิจฯ":""}</button><button className={buttonClass} disabled={busy||!reasons[a.id]?.trim()} onClick={()=>void review(a,"reject")}>ปฏิเสธ / ให้แก้ไข</button></div>}<History events={a.events}/></section>)}</Page>;
}

