"use client";
import {useEffect,useState} from "react";
import {Page,Notice,fieldClass,buttonClass} from "@/components/shared/Phase4UI";
import {requestJson,errorMessage,statusLabel,type CompetitionOption} from "@/lib/phase4-client";
import type {AnalyticsSummary,AnalyticsRow} from "@/lib/analytics";
import {getSnapshots,getSnapshot,saveSnapshot,deleteSnapshot,type SnapshotInfo,type AnalyticsSnapshot} from "@/lib/snapshot-store";
type Result={summary:AnalyticsSummary;rows:AnalyticsRow[];filters:{competitionId:string|null;sport:string|null}};
function Summary({data}:{data:AnalyticsSummary}){
 const m=data.metrics;const cards=[["ใบสมัครทั้งหมด",m.totalApplications],["นักกีฬาไม่ซ้ำ (คน)",m.uniqueAthletes],["รอพิจารณา (ใบ)",m.pending],["ผ่าน (ใบ)",m.approved],["ไม่ผ่าน (ใบ)",m.rejected],["โควตาตัวจริง + สำรอง",m.totalQuota],["อัตราเติมเต็ม",m.fillRate.toFixed(1)+"%"]];
 return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(([label,value])=><div className="rounded-lg border bg-white p-4" key={label}><p className="text-sm text-slate-600">{label}</p><p className="text-2xl font-bold text-purple-800">{value}</p></div>)}</div>{!m.totalApplications&&<p>ยังไม่มีใบสมัครตรงกับตัวกรองนี้</p>}<section className="overflow-x-auto rounded-lg border bg-white p-4"><h2 className="mb-3 font-bold">แยกตามกีฬา</h2><table className="w-full text-left"><thead><tr>{["กีฬา","ใบสมัคร","ผ่าน","โควตา","เติมเต็ม"].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data.sports.map(s=><tr key={s.sport} className="border-t"><td className="p-2">{s.sport}</td><td>{s.applications}</td><td>{s.approved}</td><td>{s.quota}</td><td>{s.fillRate.toFixed(1)}%</td></tr>)}</tbody></table></section><div className="grid gap-4 md:grid-cols-2"><section className="rounded-lg border bg-white p-4"><h2 className="font-bold">คณะ (นับใบสมัคร)</h2>{data.faculties.map(f=><p key={f.faculty}>{f.faculty}: {f.applications} · ผ่าน {f.approved}</p>)}</section><section className="rounded-lg border bg-white p-4"><h2 className="font-bold">สถานะใบสมัคร</h2>{data.statuses.map(s=><p key={s.status}>{statusLabel[s.status]}: {s.count}</p>)}</section></div><p className="rounded-lg bg-slate-100 p-4">เพศ / งบประมาณ / ผลตามเกณฑ์เฉพาะกีฬา: ยังไม่มีข้อมูล</p></div>;
}
export default function Analytics(){
 const [competitions,setCompetitions]=useState<CompetitionOption[]>([]);const [competitionId,setCompetitionId]=useState("");const [sport,setSport]=useState("");
 const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 const [snapshots,setSnapshots]=useState<SnapshotInfo[]>([]);const [snapshot,setSnapshot]=useState<AnalyticsSnapshot|null>(null);const [title,setTitle]=useState("");const [notes,setNotes]=useState("");
 useEffect(()=>{let active=true;Promise.all([requestJson<{competitions:CompetitionOption[]}>("/api/competitions"),getSnapshots()]).then(([c,s])=>{if(active){setCompetitions(c.competitions);setSnapshots(s);}}).catch(e=>{if(active)setMessage(errorMessage(e));});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;requestJson<Result>("/api/staff/analytics?"+new URLSearchParams({competitionId,sport})).then(d=>{if(active)setResult(d);}).catch(e=>{if(active)setMessage(errorMessage(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[competitionId,sport]);
 function change(comp:string,s:string){setBusy(true);setResult(null);setMessage("");setCompetitionId(comp);setSport(s);}
 async function save(){setSaving(true);setMessage("");try{await saveSnapshot({title,notes,competitionId,sport});setSnapshots(await getSnapshots());setTitle("");setNotes("");setMessage("บันทึกสรุปจากฐานข้อมูลแล้ว ไม่มีข้อมูลส่วนบุคคลรายคนใน snapshot");}catch(e){setMessage(errorMessage(e));}finally{setSaving(false);}}
 async function open(id:string){setSaving(true);try{setSnapshot(await getSnapshot(id));}catch(e){setMessage(errorMessage(e));}finally{setSaving(false);}}
 async function remove(id:string){if(!window.confirm("ลบรายงานย้อนหลังนี้?"))return;setSaving(true);try{await deleteSnapshot(id);setSnapshots(await getSnapshots());if(snapshot?.id===id)setSnapshot(null);}catch(e){setMessage(errorMessage(e));}finally{setSaving(false);}}
 function download(){
  if(!result)return;
  const escape=(v:unknown)=>'"'+String(v??"").replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
  const rows=[["รหัสนิสิต","ชื่อ","นามสกุล","คณะ","กีฬา","สถานะ","ประเภท"],...result.rows.map(r=>[r.studentId,r.firstName,r.lastName,r.faculty,r.sport,r.status,r.squadType])];
  const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(r=>r.map(escape).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));
  const a=document.createElement("a");a.href=url;a.download="athlete-applications.csv";a.click();URL.revokeObjectURL(url);
 }
 const sports=[...new Set(competitions.filter(c=>!competitionId||c.id===competitionId).flatMap(c=>c.quotas.map(q=>q.sport)))].sort();
 return <Page title="สถิติการสมัครนักกีฬา"><Notice text={message}/><div className="grid gap-4 md:grid-cols-2"><label>การแข่งขัน<select className={fieldClass} value={competitionId} disabled={saving} onChange={e=>change(e.target.value,"")}><option value="">ทุกการแข่งขัน</option>{competitions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>กีฬา<select className={fieldClass} value={sport} disabled={saving} onChange={e=>change(competitionId,e.target.value)}><option value="">ทุกกีฬา</option>{sports.map(s=><option key={s}>{s}</option>)}</select></label></div>
 <p className="text-sm text-slate-600">หน่วยหลักคือใบสมัคร นักกีฬาคนเดียวสมัครได้หลายกีฬา “ผ่าน” หมายถึงกองกิจฯ อนุมัติหรือประกาศผลแล้ว</p>{busy&&<p role="status">กำลังโหลดสถิติ…</p>}{result&&<><Summary data={result.summary}/><button className={buttonClass} onClick={download}>ส่งออก CSV ตามข้อมูลที่แสดง</button></>}
 <section className="space-y-3 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">บันทึกรายงานย้อนหลัง</h2><p className="text-sm">ระบบคำนวณยอดใหม่ขณะบันทึกตามตัวกรองด้านบน ข้อมูลย้อนหลังจะไม่เปลี่ยนตามฐานข้อมูลปัจจุบัน</p><input aria-label="ชื่อรายงาน" placeholder="ชื่อรายงาน" className={fieldClass} maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/><textarea aria-label="หมายเหตุ" placeholder="หมายเหตุ" className={fieldClass} maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/><button className={buttonClass} disabled={busy||saving||!result||!title.trim()} onClick={()=>void save()}>บันทึก snapshot</button>
 {!snapshots.length&&<p>ยังไม่มีรายงานย้อนหลัง</p>}<ul className="divide-y">{snapshots.map(s=><li key={s.id} className="flex flex-wrap items-center gap-4 py-3"><button disabled={saving} onClick={()=>void open(s.id)} className="text-purple-700 underline">{s.title}</button><span className="text-sm">{new Date(s.createdAt).toLocaleString("th-TH")}</span>{s.canDelete&&<button disabled={saving} className="text-red-700" onClick={()=>void remove(s.id)}>ลบ</button>}</li>)}</ul></section>
 {snapshot&&<section className="space-y-4 rounded-xl border-2 border-purple-300 p-5"><h2 className="text-xl font-bold">รายงานย้อนหลัง: {snapshot.title}</h2><p>{snapshot.notes} · {new Date(snapshot.createdAt).toLocaleString("th-TH")} · รูปแบบรุ่น {snapshot.schemaVersion}</p><p>ตัวกรอง: {competitions.find(c=>c.id===snapshot.filters.competitionId)?.name??snapshot.filters.competitionId??"ทุกการแข่งขัน"} / {snapshot.filters.sport??"ทุกกีฬา"}</p><Summary data={snapshot.data}/><button onClick={()=>setSnapshot(null)} className="text-purple-700 underline">ปิดรายงานย้อนหลัง</button></section>}
 </Page>;
}

