"use client";
import { useEffect,useState } from "react";
import { Page,Notice,PrivateUpload,History,fieldClass,buttonClass } from "@/components/shared/Phase4UI";
import { requestJson,errorMessage,statusLabel,type CompetitionOption,type OfficialRecord } from "@/lib/phase4-client";
import { PROFILE_FIELDS,REQUIRED_PROFILE,DOCUMENT_FIELDS,EDITABLE_OFFICIAL } from "@/lib/phase4-policy";
import { officialLabels,documentLabels,positionLabels } from "@/lib/official-labels";
type Club={id:string;name:string;sport:string};
export default function Register(){
 const [competitions,setCompetitions]=useState<CompetitionOption[]>([]);const [clubs,setClubs]=useState<Club[]>([]);const [applications,setApplications]=useState<OfficialRecord[]>([]);
 const [competitionId,setCompetitionId]=useState("");const [clubId,setClubId]=useState("");const [profile,setProfile]=useState<Record<string,string>>({nationality:"ไทย"});const [documents,setDocuments]=useState<Record<string,string>>({});
 const [current,setCurrent]=useState<OfficialRecord|null>(null);const [accepted,setAccepted]=useState(false);const [busy,setBusy]=useState(true);const [message,setMessage]=useState("");
 useEffect(()=>{let active=true;Promise.all([requestJson<{competitions:CompetitionOption[]}>("/api/competitions"),requestJson<{clubs:Club[]}>("/api/clubs"),requestJson<{applications:OfficialRecord[]}>("/api/team-official/applications")]).then(([c,b,a])=>{if(!active)return;setCompetitions(c.competitions);setClubs(b.clubs);setApplications(a.applications);const id=new URLSearchParams(window.location.search).get("competitionId");if(id){const app=a.applications.find(x=>x.competitionId===id);setCompetitionId(id);setCurrent(app??null);setClubId(app?.clubId??"");setProfile(app?.profile??{nationality:"ไทย"});setDocuments(app?.documents??{});}}).catch(e=>{if(active)setMessage(errorMessage(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[]);
 function select(id:string){const app=applications.find(a=>a.competitionId===id);setCompetitionId(id);setCurrent(app??null);setClubId(app?.clubId??"");setProfile(app?.profile??{nationality:"ไทย"});setDocuments(app?.documents??{});setAccepted(false);setMessage("");}
 async function save(action:string){setBusy(true);setMessage("");try{await requestJson("/api/team-official/applications",{competitionId,clubId,profile,documents,version:current?.version??0,action,acceptedRules:accepted});const d=await requestJson<{applications:OfficialRecord[]}>("/api/team-official/applications");setApplications(d.applications);setCurrent(d.applications.find(a=>a.competitionId===competitionId)??null);setMessage(action==="submit"?"ส่งแล้ว รอชมรมพิจารณาก่อนกองกิจฯ":"บันทึกร่างแล้ว");}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}}
 const locked=!!current&&!EDITABLE_OFFICIAL.includes(current.status);
 const sports=competitions.find(c=>c.id===competitionId)?.quotas.map(q=>q.sport)??[];
 return <Page title="ใบสมัครเจ้าหน้าที่ทีม"><Notice text={message}/>{busy&&<p role="status">กำลังดำเนินการ…</p>}<p>หนึ่งใบสมัครต่อการแข่งขัน เลือกได้หนึ่งชมรม เมื่อถูกปฏิเสธสามารถแก้ไขและส่งให้ชมรมพิจารณาใหม่</p><label>การแข่งขัน<select className={fieldClass} value={competitionId} disabled={busy} onChange={e=>select(e.target.value)}><option value="">เลือกการแข่งขัน</option>{competitions.map(c=><option value={c.id} key={c.id}>{c.name} ({c.status})</option>)}</select></label>
 {competitionId&&<section className="space-y-5 rounded-xl border bg-white p-5"><Notice text={current?statusLabel[current.status]:"ยังไม่มีใบสมัคร — กรุณากรอกข้อมูล"}/><label className="block">ชมรม (บังคับ)<select className={fieldClass} value={clubId} disabled={locked||busy} onChange={e=>setClubId(e.target.value)}><option value="">เลือกชมรม</option>{clubs.filter(c=>sports.includes(c.sport)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.sport}</option>)}</select></label>
 <div className="grid gap-4 md:grid-cols-2">{PROFILE_FIELDS.map(key=><label className="block" key={key}>{officialLabels[key]}{(REQUIRED_PROFILE as readonly string[]).includes(key)?" *":""}{key==="appliedPosition"?<select className={fieldClass} disabled={locked||busy} value={profile[key]??""} onChange={e=>setProfile({...profile,[key]:e.target.value})}><option value="">เลือกตำแหน่ง</option>{Object.entries(positionLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input className={fieldClass} disabled={locked||busy} type={key==="birthDate"?"date":key==="email"?"email":"text"} maxLength={key==="nationalId"?13:1000} value={profile[key]??""} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>}</label>)}</div>
 <div className="grid gap-4 md:grid-cols-2">{DOCUMENT_FIELDS.map(key=><PrivateUpload key={key} label={documentLabels[key]} value={documents[key]??""} onChange={id=>setDocuments(d=>({...d,[key]:id}))} disabled={busy||locked} retained={!!current?.events.some(e=>e.action==="SUBMITTED")}/>)}</div>
 {!locked&&<><label className="flex gap-2"><input type="checkbox" checked={accepted} disabled={busy} onChange={e=>setAccepted(e.target.checked)}/>ยืนยันความถูกต้องของข้อมูล เอกสาร และยอมรับระเบียบการแข่งขัน</label><div className="flex gap-3"><button className={buttonClass} disabled={busy||!clubId} onClick={()=>void save("save")}>บันทึกร่าง</button><button className={buttonClass} disabled={busy||!clubId||!accepted||!documents.plan||!documents.idCard} onClick={()=>void save("submit")}>ส่งใบสมัคร</button><button className="text-purple-700 underline" disabled={busy} onClick={()=>window.location.reload()}>โหลดข้อมูลล่าสุด</button></div></>}
 <History events={current?.events??[]}/></section>}</Page>;
}

